<?php

namespace App\Filament\Resources\Permissions;

use App\Filament\Resources\Permissions\Pages\ListPermissions;
use App\Filament\Resources\Permissions\Tables\PermissionsTable;
use BackedEnum;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Support\Icons\Heroicon;
use Filament\Tables\Table;
use Spatie\Permission\Models\Permission;

/**
 * Slice 2 / PR 2 — REQ-ADV-2 "Admin Panel Role and Permission UI".
 *
 * PermissionResource is INTENTIONALLY read-only: there is no Create /
 * Edit / View page, only the list page. Permission records are
 * generated by `php artisan shield:generate --all` (or
 * `shield:super-admin`) which scans the Filament Resources + Pages +
 * Widgets and writes one Permission row per discovered policy method.
 *
 * This split matches the design.md Decision 4 boundary: Shield owns
 * permission generation; the admin UI only lets the admin SEE the
 * generated permissions (so they can be assigned to roles via the
 * RoleResource permissions CheckboxList). Manual permission creation
 * from the admin panel would race with `shield:generate` and is
 * explicitly out of scope.
 */
class PermissionResource extends Resource
{
    protected static ?string $model = Permission::class;

    protected static string|BackedEnum|null $navigationIcon = Heroicon::OutlinedKey;

    protected static ?string $navigationLabel = 'Permissions';

    protected static ?string $modelLabel = 'Permission';

    protected static ?string $pluralModelLabel = 'Permissions';

    public static function form(Schema $schema): Schema
    {
        // No form — permissions are generated by `shield:generate`.
        // Returning an empty schema keeps the Resource contract happy
        // (Filament's Create/Edit pages derive their form from this).
        return $schema;
    }

    public static function table(Table $table): Table
    {
        return PermissionsTable::configure($table);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => ListPermissions::route('/'),
        ];
    }
}
